federation_version: =2.6.3

subgraphs:
  user-service:
    routing_url: http://user-service:5000/graphql
    schema:
      subgraph_url: http://user-service:5000/graphql

  company-service:
    routing_url: http://company-service:8080/graphql
    schema:
      subgraph_url: http://company-service:8080/graphql

#  translation-service:
#    routing_url: http://translation-service:8083/graphql
#    schema:
#      subgraph_url: http://translation-service:8083/graphql

  shop-service:
    routing_url: http://shop-service:5003/graphql
    schema:
      subgraph_url: http://shop-service:5003/graphql

  masterdata-service:
    routing_url: http://masterdata-service:5002/graphql
    schema:
      subgraph_url: http://masterdata-service:5002/graphql

  orders-service:
    routing_url: http://orders-service:5004/graphql
    schema:
      subgraph_url: http://orders-service:5004/graphql

  accounting-service:
     routing_url: http://accounting-service:5001/graphql
     schema:
       subgraph_url: http://accounting-service:5001/graphql

#  notification-service:
#     routing_url: http://notification-service:8082/graphql
#     schema:
#       subgraph_url: http://notification-service:8082/graphql

#  scripting-service:
#     routing_url: http://localhost:8085/graphql
#     schema:
#       subgraph_url: http://localhost:8085/graphql
