spring:
  graphql:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration
      - org.springframework.boot.autoconfigure.graphql.servlet.GraphQlWebMvcAutoConfiguration
